version: '3.8'
services:
  db:
    container_name: spycat_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: spycat_test
    ports:
      - "5777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: